//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8670
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IService1")]
public interface IService1
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/subscribe", ReplyAction="http://tempuri.org/IService1/subscribeResponse")]
    bool subscribe(string topic, string recipientName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/publish", ReplyAction="http://tempuri.org/IService1/publishResponse")]
    bool publish(string topic, string payload);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPublications", ReplyAction="http://tempuri.org/IService1/GetPublicationsResponse")]
    string[] GetPublications(string topic, string subscriber);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IService1Channel : IService1, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class Service1Client : System.ServiceModel.ClientBase<IService1>, IService1
{
    
    public Service1Client()
    {
    }
    
    public Service1Client(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public Service1Client(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public bool subscribe(string topic, string recipientName)
    {
        return base.Channel.subscribe(topic, recipientName);
    }
    
    public bool publish(string topic, string payload)
    {
        return base.Channel.publish(topic, payload);
    }
    
    public string[] GetPublications(string topic, string subscriber)
    {
        return base.Channel.GetPublications(topic, subscriber);
    }
}
